spring:
  datasource:
    url: jdbc:h2:~/liquibase;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
  liquibase.change-log: changelog/liquidbase-changelog.xml