spring:
  datasource:
    url: jdbc:h2:~/liquibase;DB_CLOSE_ON_EXIT=TRUE
    username: sa
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
  liquibase.change-log: classpath:changelog/liquidbase-changelog.xml